#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X


#### BSPWM configuration ####
bspc config border_width                  0
bspc config window_gap                    15
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_by_distance             true
bspc config history_aware_focus           true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color '#20202a'
bspc config active_border_color '#4c5664'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a firefox:Picture-in-picture state=floating
bspc rule -a Zathura state=tiled
bspc rule -a scpad state=floating sticky=on rectangle=1800x1000+60+50
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
hsetroot -solid "#13131A"
# feh --bg-fill ~/Images/walls/cw.png
