return {
  'shaunsingh/nord.nvim',
  "mhinz/vim-sayonara",
  "jiangmiao/auto-pairs",
  "nvim-treesitter/nvim-treesitter",
  "JoosepAlviste/nvim-ts-context-commentstring",
  "mrjones2014/nvim-ts-rainbow",
  "nvim-lualine/lualine.nvim",
  "brenoprata10/nvim-highlight-colors",
  -- "noib3/nvim-cokeline",
  "max397574/better-escape.nvim",
  "ur4ltz/surround.nvim",
  --"ziontee113/color-picker.nvim",
  "ziontee113/icon-picker.nvim",
  "stevearc/dressing.nvim", --> For icon-picke,
  "ethanholz/nvim-lastplace",
  ---- LSP
  "neovim/nvim-lspconfig",
  --
  --"folke/lsp-colors.nvim",
  --"jose-elias-alvarez/null-ls.nvim",
  ---- Make into an IDE --
  -- "weilbith/nvim-code-action-menu",
  "simrat39/symbols-outline.nvim",
  "nvim-tree/nvim-tree.lua",
  --"petertriho/nvim-scrollbar",
  "nvim-telescope/telescope.nvim",
  "nvim-lua/plenary.nvim",
  --"folke/which-key.nvim",
  --
  ---- COMPLETIONS
  "hrsh7th/cmp-nvim-lsp",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/nvim-cmp",
  "lukas-reineke/cmp-under-comparator",
  "SirVer/ultisnips",
  "quangnguyen30192/cmp-nvim-ultisnips",
  --"ray-x/cmp-treesitter",
  "nvim-tree/nvim-web-devicons",
  --
  ---- UI ELEMENTS
  "folke/noice.nvim",
  "MunifTanjim/nui.nvim",
  "rcarriga/nvim-notify",
  -- "karb94/neoscroll.nvim",
  -- "glepnir/dashboard-nvim",
  "lukas-reineke/indent-blankline.nvim",
}
