require("chills.setups.Comment")
require("chills.setups.better-escape")
require("chills.setups.colorscheme")
require("chills.setups.cokeline")
require("chills.setups.mason")
require("chills.setups.lspui")
require("chills.setups.nvimlsp")
require("chills.setups.nvimcmp")
require("chills.setups.telescope")
require("chills.setups.nvim-highlight-colors")
require("chills.setups.surround")
require("chills.setups.neoscroll")
require("chills.setups.treesitter")
-- require("chills.setups.lualine")
require("chills.setups.codeactions")
require("chills.setups.symbolsoutline")
require("chills.setups.icons")
require("chills.setups.nvimnotify")
require("chills.setups.noice")
require("chills.setups.nvimtree")
require("chills.setups.dressing")
require("chills.setups.lastplace")
require("chills.setups.dashboard")
require("chills.setups.indent-blankline")
-- require("user.setups.colorpicker")
-- require("user.setups.nullls")
-- require("user.setups.gotopreview")
-- require("user.setups.scrollbar")
-- require("user.setups.nvimtsrefactor")
