require("chills.setups.Comment")
require("chills.setups.better-escape")
require("chills.setups.aquarium")
require("chills.setups.cokeline")
require("chills.setups.mason")
require("chills.setups.lspui")
require("chills.setups.nvimlsp")
require("chills.setups.nvimcmp")
require("chills.setups.telescope")
require("chills.setups.nvim-highlight-colors")
require("chills.setups.surround")
require("chills.setups.neoscroll")
-- require("user.setups.treesitter")
-- require("user.setups.nvimnotify")
-- require("user.setups.noice")
-- require("user.setups.dressing")
-- require("user.setups.lualine")
-- require("user.setups.codeactionsmenu")
-- require("user.setups.colorpicker")
-- require("user.setups.icons")
-- require("user.setups.nullls")
-- require("user.setups.gotopreview")
-- require("user.setups.symbolsoutline")
-- require("user.setups.scrollbar")
-- require("user.setups.nvimtsrefactor")

